version: "3.5"

volumes:
  nextcloud-onlyoffice:

secrets:
  nextcloud_nextcloud_onlyoffice_password:
    name: ${STACK_NAME:-technocore}_nextcloud_nextcloud_onlyoffice_password
    external: true
  nextcloud_onlyoffice_nextcloud_password:
    name: ${STACK_NAME:-technocore}_nextcloud_onlyoffice_nextcloud_password
    external: true

services:


  nextcloud_onlyoffice:
    deploy:
      labels:
        # TODO: Add virtual path: https://github.com/ONLYOFFICE/document-server-proxy/blob/master/traefik/proxy-to-virtual-path.toml
        # Needed in most of the onlyoffice guides:
        - traefik.frontend.passHostHeader=true
        #- ${TRAEFIK_BASIC_AUTH}
        - traefik.frontend.rule=$NEXTCLOUD_ONLYOFFICE_ROUTING_LABEL
        - traefik.frontend.priority=$NEXTCLOUD_ONLYOFFICE_ROUTING_LABEL_PRIORITY
        - traefik.port=80        
        - traefik.enable=true
        - traefik.tags=ingress 
        - traefik.docker.network=${STACK_NAME:-technocore}_nextcloud
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
      mode: global
      restart_policy:
        condition: any
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET={{"{{DOCKER-SECRET:nextcloud_password}}"}}
    image: ${image_provider:-scififarms}/technocore-nextcloud-onlyoffice:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - nextcloud
    secrets:
      - source: nextcloud_onlyoffice_nextcloud_password
        target: nextcloud_password
    volumes:
      - nextcloud-onlyoffice:/var/www/onlyoffice/Data
  
  nextcloud:
    environment:
      - NEXTCLOUD_ONLYOFFICE_PASSWORD={{"{{DOCKER-SECRET:nextcloud_onlyoffice_password}}"}}
    secrets:
      - source: nextcloud_nextcloud_onlyoffice_password
        target: nextcloud_onlyoffice_password

